<a href="https://colab.research.google.com/github/Tarleton-Math/data-science-20-21-hwk03/blob/master/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Homework 03
## Data Science (masters)
## Math 5364 & 5366, Fall 20 & Spring 21
## Tarleton State University
## Dr. Scott Cook
## Due 2020-09-17

# Setup

In [2]:
import os
import google.colab
import getpass

preferred_path = f"My Drive/active/m53646-data-science-20-21/as-student/hwk"   # your preferred google drive path
root_path = "/content/drive/"
hwk_num = "03"

## This newer version let's you set defaults and choose to keep or overwrite
## credentials you already entered.  I think it'll reduce the amount of copy/paste.
## It also shows what you are typing for non-secure credentials &
## gives up on the idea of cloning both your repo and mine.
## Just clone yours - I'll announce if any changes occur to a homework set.

try:
    git['user']
except:
    git = {'user' : 'drscook',
           'email': 'scook@tarleton.edu'}

for var, secure in [['user', False], ['token', True], ['email', False]]:
    prompt = f'Enter your github {var} '
    try:
        git[var]
        prompt += 'or press enter to use existing '
        if secure:
            prompt += '*' * len(git[var])
            new_var = getpass.getpass(prompt)
        else:
            prompt += f'"{git[var]}" '
            new_var = input(prompt)
        if new_var != "":
            git[var] = new_var
    except:
        if secure:
            git[var] = getpass.getpass(prompt)
        else:
            git[var] = input(prompt)

git['repo'] = f"data-science-20-21-hwk{hwk_num}"
if git['user'] != "drscook" and git['user'] != "":
    git['repo'] += f"-{git['user']}"  # appends your username
git['url'] = f"https://{git['user']}:{git['token']}@github.com/Tarleton-Math/{git['repo']}.git"  # url to your origin repo
git['path'] = os.path.join(root_path, preferred_path, git['repo'])  # path to folder for your local repo
! git config --global user.name "{git['user']}"    # set git info
! git config --global user.email "{git['email']}"  # set git info

google.colab.drive.mount(root_path)
os.makedirs(git['path'], exist_ok=True)  # create path if necessary
%cd "{git['path']}"

def push(msg=f"enter commit message here"):
    %cd "{git['path']}"
    ! git add .  # Add any new files
    ! git commit -a -m "{msg}"  # Commit changes
    ! git push  # push changes from your local to your orign

def pull():
    %cd "{git['path']}"
    ! git pull  # pull changes from your origin to your local

def clone():
    %cd "{git['path']}"
    ! git clone "{git['url']}" .

clone()
pull()

Enter your github user or press enter to use existing "drscook" 
Enter your github token ··········
Enter your github email or press enter to use existing "scook@tarleton.edu" 
Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).
/content/drive/My Drive/active/m53646-data-science-20-21/as-student/hwk/data-science-20-21-hwk03
/content/drive/My Drive/active/m53646-data-science-20-21/as-student/hwk/data-science-20-21-hwk03
fatal: destination path '.' already exists and is not an empty directory.
/content/drive/My Drive/active/m53646-data-science-20-21/as-student/hwk/data-science-20-21-hwk03
Already up to date.


In [ ]:
push()

In [140]:
!pip install --upgrade numpy
!pip install --upgrade pandas

Requirement already up-to-date: numpy in /usr/local/lib/python3.6/dist-packages (1.19.1)
     |████████████████████████████████| 10.5MB 2.9MB/s 
ERROR: google-colab 1.0.0 has requirement pandas~=1.0.0; python_version >= "3.0", but you'll have pandas 1.1.2 which is incompatible.
  Found existing installation: pandas 1.0.5
    Uninstalling pandas-1.0.5:
      Successfully uninstalled pandas-1.0.5


In [138]:
pd.__version__

'1.0.5'

# Homework

Consider the famous iris dataset popularized by RA Fisher which contains 4 physical measurements from 150 irises of 3 types: setosa, versicolour, and virginica.  It is available in many many places; I got it here:

https://archive.ics.uci.edu/ml/datasets/Iris

In [34]:
# !pip install --upgrade numpy
# !pip install --upgrade pandas
import numpy as np
import pandas as pd
rng = np.random.default_rng(42)

feat = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
df = pd.read_csv("iris.data", names=feat+['class'])

classes = df['class'].unique()
targ = []
for cl in classes:
    t = cl+'_indicator' 
    df[t] = (df['class'] == cl)
    targ.append(t)


df = df.sample(frac=1, random_state=rng.bit_generator)
holdout_frac = 0.1
n, p = df.shape
m = int(n * holdout_frac)
mask = np.zeros(n, bool)
mask[:m] = True

# X_holdout, Y_holdout = df.loc[mask, feat], df.loc[mask, targ]
# X_model  , Y_model   = df.loc[~mask, feat], df.loc[~mask, targ]
# print(X_holdout.shape, X_model.shape, Y_holdout.shape, Y_model.shape)

df_holdout = df[mask]
df_model   = df[~mask]
# print(X_holdout.shape, X_model.shape, Y_holdout.shape, Y_model.shape)

In [21]:
df.sample?

In [50]:
cv_folds = 1
n, p = df_model.shape
cv_fold_size = n / 10
start_idx = 0

def cross_subtract(X, Y):
    return X[:,np.newaxis] - Y[np.newaxis]

# def knn(X, Y, train_mask):




# DX = cross_subtract(X, X)
# DY = cross_subtract(Y, Y*0)

# p = 2
# k = 4
# D = ((DX**p).sum(axis=-1))**(1/p)

# srt = np.argpartition(D, k)
# srt = srt[:, 1:k+1]
# srt.shape
# # np.take_along_axis(DY, srt, axis=1)
# DY[srt].shape


# # DY[srt].shape
# .sum(axis=-1)


def knn(d, k=4, p=2):
    DX = cross_subtract(d['X_train'].to_numpy(), d['X_valid'].to_numpy())
    DY = cross_subtract(d['Y_train'].to_numpy(), d['Y_valid'].to_numpy()*0)

    D = ((DX**p).sum(axis=-1))**(1/p)
    srt = np.argpartition(D, k)
    return DY


for fold in range(cv_folds):
    stop_idx = int(start_idx + cv_fold_size)
    mask = np.zeros(n, bool)
    mask[start_idx:stop_idx] = True
    d = {'X_valid': df_model.loc[ mask, feat],
         'Y_valid': df_model.loc[ mask, targ],
         'X_train': df_model.loc[~mask, feat],
         'Y_train': df_model.loc[~mask, targ],
         }
    DY = knn(d)



(122, 13, 4)
(122, 13, 3)


In [51]:
DY[0]

array([[0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0]])

In [130]:
rng = np.random.RandomState(42)

In [128]:
n, p = df.shape
df = df.iloc[rng.permutation(n)]
df

sepal_length  ...  Iris-virginica_indicator
22            4.6  ...                     False
112           6.8  ...                      True
94            5.6  ...                     False
67            5.8  ...                     False
109           7.2  ...                      True
..            ...  ...                       ...
68            6.2  ...                     False
56            6.3  ...                     False
10            5.4  ...                     False
19            5.1  ...                     False
16            5.4  ...                     False

[150 rows x 8 columns]

In [116]:
import numpy as np
import pandas as pd

df = pd.read_csv("iris.data", names=['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class'])
df


sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [117]:
df.iloc[[9,37]]

sepal_length  sepal_width  petal_length  petal_width        class
9            4.9          3.1           1.5          0.1  Iris-setosa
37           4.9          3.1           1.5          0.1  Iris-setosa

In [39]:
A = np.arange(4)
D = A[np.newaxis] - A[:,np.newaxis]
D[1,0]

-1

In [59]:
A = np.random.rand(5)
srt = np.argpartition(A, 1)
print(A)
print(srt)
print(A[srt])

[0.78684158 0.23104249 0.35325468 0.31467846 0.66705912]
[1 3 2 0 4]
[0.23104249 0.31467846 0.35325468 0.78684158 0.66705912]


In [118]:
df.sample?

In [88]:
df_holdout = df.sample

X = df.iloc[:,:4].to_numpy()
Y = df.iloc[:,5:].to_numpy()




def cross_subtract(X, Y):
    return X[np.newaxis] - Y[:,np.newaxis]

def knn(X, Y, train_mask):
    X_train, X_validate = X[train_mask], X[~train_mask]
    Y_train, Y_validate = Y[train_mask], Y[~train_mask]




DX = cross_subtract(X, X)
DY = cross_subtract(Y, Y*0)

p = 2
k = 4
D = ((DX**p).sum(axis=-1))**(1/p)

srt = np.argpartition(D, k)
srt = srt[:, 1:k+1]
srt.shape
# np.take_along_axis(DY, srt, axis=1)
DY[srt].shape


# DY[srt].shape
# .sum(axis=-1)


# srt.shape

# srt
# DY[48,100]
# np.argpartition?

(150, 4, 150, 3)

In [115]:
X = df.iloc[:,:4].to_numpy()
Y = df.iloc[:,5:].to_numpy()

DX = X[np.newaxis] - X[:,np.newaxis]
DY = Y[np.newaxis] - Y[:,np.newaxis]*0

p = 2
k = 0
D = ((np.abs(DX)**p).sum(axis=-1))**(1/p)

# srt = np.partition(D, k)[:,k]
# srt.shape
# D.shape
# mask = D <= srt
# Y[srt]
# mask.sum(axis=-1)
# mask.sum(axis=1)
np.argsort(D[9], k)
X[[9,34]]


array([[4.9, 3.1, 1.5, 0.1],
       [4.9, 3.1, 1.5, 0.1]])

1. Read data-science-20-21-notes-20-08-26.ipynb.  Note that I didn't give you the function my_PCA.
1. Write your own my_PCA function using basic commands and the list of more advance ones below.  There are lots commands that will do the work of you, but the goal is to use this data science related task to hone your basic Python skills.  Please send me an email if you have questions about what yo can use.
    - df.mean(axis=???) - row/columns means
    - np.dot - matrix multiplications (or use the @ operator between the matrices)
    - np.linalg.eigs - get eigenvalues and eigenvectors
    - np.argsort - to sort BOTH eigenvalues and eigenvectors the same
        - np.argsort sorts smallest to largest, but you want largest to smallest.  Use [::-1] to reverse a list/1D array in Python.
    - np.diag - create a diagonal matrix
1. Use your my_PCA to fill the missing functino in my notes and confirm that you get the same results.
1. Use your my_PCA on the 4 quantitative columns of the iris dataset.
1. Check your results against the "black box" PCA from scikit-learn.
    - You and scikit-learn may disagree on signs.  More precisely, your column j might contain all the same numbers as scikit-learn's column j except all signs are flipped.  That's okay.
    - Even in my own notes, scikit-learn's x' axis was flipped from mine.